name: "Build Docker Images"

on:
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        tag: ["8.1.29", "8.2.20", "8.3.8"]
        zts: ['yes', 'no']
        debug: ['yes', 'no']
        ubuntu_version: ["20.04", "22.04", "24.04"]
    uses: "./.github/workflows/docker-image.yml"
    with:
      php: ${{ matrix.tag }}
      zts: ${{ matrix.zts }}
      ubuntu_version: ${{ matrix.ubuntu_version }}
      debug: ${{ matrix.debug }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
