name: "Test PHP Extension"

on:
  workflow_call:
  push:
    branches:
      - v1.3.x
  pull_request:
    branches:
      - v1.3.x
jobs:
  test:
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.1-zts', '8.2-zts', '8.3-zts']
        os: ['ubuntu-20.04', 'ubuntu-24.04']
        preset: ['CICassandraDebug', 'CIScyllaDebug']
      fail-fast: false
    runs-on: ubuntu-latest
    container: malusevd99/scylladb-php-driver:${{ matrix.os }}-php-${{ matrix.php }}-debug
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Run tests
        run: |
          cmake --preset ${{ matrix.preset }} || exit 1

          cd out/${{ matrix.preset }} || exit 1
          ninja install || exit 1
          cd ../../

          cat cassandra.ini >> "$(php-config --ini-path | xargs -I {} printf '%s/php.ini' {})" || exit 1

          cd tests
          composer install
          php ./vendor/bin/pest
